[stat]
host = "stat.mydb.com"
port = "1234"
dbname = "stat"
username = "stat_writer"
password = {_var = "MYAPP_DBPASS_STAT"}
options = {_var = "myapp.db.defaultOptions"}

[metrics]
host = "metrics.mydb.com"
port = "1234"
dbname = "metrics"
username = "metrics_writer"
password = {_var = "MYAPP_DBPASS_METRIC"}
options = {_var = "...defaultOptions"}