[stat]
host = "stat.mydb.com"
port = 1234
dbname = "stat"
username = "stat_writer"
password = {_var = "MYAPP_DB_STAT_PASS"}
options = {_var = "db.defaultOptions"}

[metrics]
host = "metrics.mydb.com"
port = 1234
dbname = "metrics"
username = "metrics_writer"
password = {_var = "MYAPP_DB_METRICS_PASS"}
options = {_var = "...defaultOptions"}