[stat]
host = "stat.mydb.com"
port = 1234
dbname = "stat"
username = "stat"
options = {"$ref" = "db.defaultOptions"}
  [stat.password]
  "$ref" = {name = "MYAPP_DB_STAT_PASSWORD", default = "stat_pass"}

[metrics]
host = "metrics.mydb.com"
port = 1234
dbname = "metrics"
username = "metrics"
options = {"$ref" = "db.defaultOptions"}
  [metrics.password]
  "$ref" = {name = "MYAPP_DB_METRICS_PASSWORD", default = "metrics_pass"}